# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - aps-OMU-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      BCRYPT_ROUNDS: ${{ secrets.BCRYPT_ROUNDS }}
      NODE_ENV: 'production'  # 必要に応じて

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Create .env.local file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env.local
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env.local
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env.local
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env.local
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env.local
          echo "DATABASE_SSL=${{ secrets.DATABASE_SSL }}" >> .env.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.local
          echo "BCRYPT_ROUNDS=${{ secrets.BCRYPT_ROUNDS }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local

      - name: Build Test  
        run:  |  
            npm run build --if-present
            npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-OMU-01'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA904367FC004ECAAE4D3F2BF86475F7 }}