# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - aps-OMU-01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_SSL: ${{ secrets.DATABASE_SSL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      BCRYPT_ROUNDS: ${{ secrets.BCRYPT_ROUNDS }}
      NODE_ENV: '' 

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js #version
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Create .env.local file
        run: |
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env.local
          echo "DATABASE_PORT=${{ secrets.DATABASE_PORT }}" >> .env.local
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env.local
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env.local
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> .env.local
          echo "DATABASE_SSL=${{ secrets.DATABASE_SSL }}" >> .env.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.local
          echo "BCRYPT_ROUNDS=${{ secrets.BCRYPT_ROUNDS }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local

      - name: Build Next.js app 
        run:  |  
            npm run build

      - name: Copy artifact for deployment job
        run: |
          mkdir deploy
          cp -r ./.next/standalone/. ./deploy
          cp -r ./.next/static/. ./deploy/.next/static
          cp package.json ./deploy/
          cp -r node_modules ./deploy/node_modules 

      - name: Zip artifact for deployment
        run: zip release.zip ./deploy -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Extract deployment package
        run: unzip release.zip  
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aps-OMU-01'
          slot-name: 'Production'
          package: './deploy'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA904367FC004ECAAE4D3F2BF86475F7 }}